package org.askie01.customers.entity;

import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;
import lombok.Data;

/**
 * Abstract base class for all entities, providing a common ID field.
 * <p>
 * This class defines a primary key identifier field {@code id}, which is
 * automatically generated and serves as the primary key and inheriting entities.
 * </p>
 * <p>
 * The {@code id} field is annotated with {@link Id} and {@link GeneratedValue}
 * to use an auto-increment strategy for generating unique values.
 * </p>
 * <p>
 * Entities that extends this class inherit the {@code id} field, eliminating
 * the need to define it in each entity class.
 * </p>
 *
 * @see jakarta.persistence.Id
 * @see jakarta.persistence.GeneratedValue
 */
@Data
@MappedSuperclass
public class BaseEntity {

    /**
     * The primary key identifier the entity.
     * <p>
     * This field is automatically generated by the persistence provider
     * using the {@link GenerationType#IDENTITY} strategy.
     * </p>
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
}
